$f = "e:\FoundryVTT\Data\systems\mega\templates\pnj-actor-sheet.html"
$c = [IO.File]::ReadAllText($f, [Text.Encoding]::UTF8)
$nl = "`r`n"
$t10 = "`t" * 10; $t11 = "`t" * 11; $t12 = "`t" * 12; $t13 = "`t" * 13

$oldArd = ($t10 + '<span class="tpc-name traits_rollable"' + $nl + $t11 + 'value="ardence">{{system.caracs.ardence.label}}</span>' + $nl + $t10 + '<div class="tpc-dots">' + $nl + $t11 + '{{#each (range system.pts_ardence.max)}}' + $nl + $t11 + '<span' + $nl + $t12 + 'class="tpc-dot {{#ifsuperior this ../system.pts_ardence.value}}tpc-dot--empty{{else}}tpc-dot--filled{{/ifsuperior}}"></span>' + $nl + $t11 + '{{/each}}' + $nl + $t10 + '</div>')
$newArd = ($t10 + '<span class="tpc-name traits_rollable"' + $nl + $t11 + 'value="ardence">{{system.caracs.ardence.label}}</span>' + $nl + $t10 + '<div class="tpc-dots-row">' + $nl + $t11 + '{{#unless system.verouille}}<button class="pts-adj-btn pts-adj-dec" data-field="system.pts_ardence.max" type="button">-</button>{{/unless}}' + $nl + $t11 + '<div class="tpc-dots" data-field="system.pts_ardence.value" data-max-field="system.pts_ardence.max">' + $nl + $t12 + '{{#each (range system.pts_ardence.max)}}' + $nl + $t12 + '<span data-dot-index="{{this}}"' + $nl + $t13 + 'class="tpc-dot {{#ifsuperior this ../system.pts_ardence.value}}tpc-dot--empty{{else}}tpc-dot--filled{{/ifsuperior}}"></span>' + $nl + $t12 + '{{/each}}' + $nl + $t11 + '</div>' + $nl + $t11 + '{{#unless system.verouille}}<button class="pts-adj-btn pts-adj-inc" data-field="system.pts_ardence.max" type="button">+</button>{{/unless}}' + $nl + $t10 + '</div>')
$oldRes = ($t10 + '<span class="tpc-name traits_rollable"' + $nl + $t11 + 'value="resonnance">{{system.caracs.resonnance.label}}</span>' + $nl + $t10 + '<div class="tpc-dots">' + $nl + $t11 + '{{#each (range system.pts_ardence.max)}}' + $nl + $t11 + '<span' + $nl + $t12 + 'class="tpc-dot {{#ifsuperior this ../system.pts_ardence.value}}tpc-dot--empty{{else}}tpc-dot--filled{{/ifsuperior}}"></span>' + $nl + $t11 + '{{/each}}' + $nl + $t10 + '</div>')
$newRes = ($t10 + '<span class="tpc-name traits_rollable"' + $nl + $t11 + 'value="resonnance">{{system.caracs.resonnance.label}}</span>' + $nl + $t10 + '<div class="tpc-dots-row">' + $nl + $t11 + '{{#unless system.verouille}}<button class="pts-adj-btn pts-adj-dec" data-field="system.pts_resonnance.max" type="button">-</button>{{/unless}}' + $nl + $t11 + '<div class="tpc-dots" data-field="system.pts_resonnance.value" data-max-field="system.pts_resonnance.max">' + $nl + $t12 + '{{#each (range system.pts_resonnance.max)}}' + $nl + $t12 + '<span data-dot-index="{{this}}"' + $nl + $t13 + 'class="tpc-dot {{#ifsuperior this ../system.pts_resonnance.value}}tpc-dot--empty{{else}}tpc-dot--filled{{/ifsuperior}}"></span>' + $nl + $t12 + '{{/each}}' + $nl + $t11 + '</div>' + $nl + $t11 + '{{#unless system.verouille}}<button class="pts-adj-btn pts-adj-inc" data-field="system.pts_resonnance.max" type="button">+</button>{{/unless}}' + $nl + $t10 + '</div>')
Write-Host "Ardence: $($c.Contains($oldArd))"; Write-Host "Resonnance: $($c.Contains($oldRes))"
if ($c.Contains($oldArd)) { $c = $c.Replace($oldArd, $newArd); Write-Host "Ard OK" }
if ($c.Contains($oldRes)) { $c = $c.Replace($oldRes, $newRes); Write-Host "Res OK" }
[IO.File]::WriteAllText($f, $c, [Text.Encoding]::UTF8); Write-Host "Done: $($c.Length)"